//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace PokeFilename.API.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class PokeFilename : global::System.Configuration.ApplicationSettingsBase
    {

        private static PokeFilename defaultInstance = ((PokeFilename)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PokeFilename())));

        public static PokeFilename Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AnubisNamer")]
        [Category("Entity Namer Selection"), Description("Select an entity namer preset")]
        public EntityNamers PKMNamer
        {
            get
            {
                return ((EntityNamers)(this["PKMNamer"]));
            }
            set
            {
                this["PKMNamer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Species} - {Nickname} - {PID}")]
        [Category("CustomNamer Settings"), Description("PKM Name format for Regular Pokemon")]
        public string RegularFormat
        {
            get
            {
                return ((string)(this["RegularFormat"]));
            }
            set
            {
                this["RegularFormat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Species} - {Nickname} - {PID}")]
        [Category("CustomNamer Settings"), Description("PKM Name format for Gameboy Pokemon")]
        public string GameboyFormat
        {
            get
            {
                return ((string)(this["GameboyFormat"]));
            }
            set
            {
                this["GameboyFormat"] = value;
            }
        }
    }
}
